### ISSUE TITLE
M2

### ISSUE THREAD

**Issue by BillingsAm3** [Zighome24/CS2340_GoGreek#2]
## Task Details
- [ ] Set up git on each person's machine
- [ ] Edit person 1 java file
- [ ] Edit person 2 java file
- [ ] Edit person 3 java file
- [ ] Edit person 4 java file
- [ ] Edit person 5 java file
- [ ] Add person 1 text file
- [ ] Add person 2 text file
- [ ] Add person 3 text file
- [ ] Add person 4 text file
- [ ] Add person 5 text file
- [ ] Delete person 1 useless file
- [ ] Delete person 2  useless file
- [ ] Delete person 3 useless file
- [ ] Delete person 4 useless file
- [ ] Delete person 5 useless file
- [ ] Create build files
