### ISSUE TITLE
As a User, I want to be able to login so that I can use the application

### ISSUE THREAD

**Issue by Zighome24** [Zighome24/CS2340_GoGreek#23]
# Task:
- [ ] Create the UI for the login screen
- [ ] Include a text input for username and password
- [ ] Include a button to submit the username and password
- [ ] Notify the user when the given username and password is incorrect
- [ ] Include a button to get out of the login screen and back to the home screen
- [ ] Test the design in landscape / portrait 

# Given, When, Then
### Given:
- A valid username,
- A valid password

###  When:
- The user clicks the login button

### Then:
- The system lets the user log in

### Given: 
- A valid username,
- An invalid password,

### When:
- The user clicks the login button

### Then:
- An error message pops up notifying the user of an incorrect username or password.

### Given: 
- An invalid username,
- A valid password,

### When:
- The user clicks the login button

### Then:
- An error message pops up notifying the user of an incorrect username or password.

### Given: 
- Any combination of inputs

### When:
- The user clicks the return to home-screen button

### Then:
- The user is returned to the home screen.

Done Done Criteria
---
- [ ] All of the tasks deemed necessary (ones not crossed out), and any additional tasks, are  completed
- [ ] The developer has tested all of the Given, When, Then scenarios.
- [ ] The developer has cleaned the UI and UX elements
- [ ] The developer has contacted another developer to check their code
- [ ] The developer has created a checkpoint commit and pushed it to the respective remote branch
