### ISSUE TITLE
As a user, I want to be able to view rat sightings on map to see their location

### ISSUE THREAD

**Issue by willeppy** [Zighome24/CS2340_GoGreek#25]
# Task:
- [ ] Interface with google maps API to get map on screen
- [ ] Import rat sighting data points
- [ ] Place points onto map
- [] Incorporate filters such as time / certain locations in city

# Given, When, Then
### Given:
- A valid user

###  When:
- The user clicks on the map tab

### Then:
- The system displays a map with pins of rat sightings 

### Given: 
- Any combination of inputs

### When:
- The user clicks the return to home-screen button

### Then:
- The user is returned to the home screen.

Done Done Criteria
---
- [ ] All of the tasks deemed necessary (ones not crossed out), and any additional tasks, are  completed
- [ ] The developer has tested all of the Given, When, Then scenarios.
- [ ] The developer has cleaned the UI and UX elements
- [ ] The developer has contacted another developer to check their code
- [ ] The developer has created a checkpoint commit and pushed it to the respective remote branch
