### ISSUE TITLE
As a new user, I want to be able to register by entering the required information, such as name, id, and password.

### ISSUE THREAD

**Issue by nworthington16** [Zighome24/CS2340_GoGreek#29]
# Task:

- [ ] Create a UI for the registration screen
- [ ] Add a text input for the user's full name
- [ ] Add a text input for the user's username
- [ ] Add a text input for the user's password
- [ ] Add a text input for the user's password confirmation
- [ ] Include a button to submit the user's entered information
- [ ] Include a button to return to the home screen
- [ ] Notify the user when a username is already taken
- [ ] Notify the user when the password confirmation does not match the first
- [ ] Test design in landscape / portrait

# Given, When, Then
# 1
**Given:**
- A valid name, username, password, and password confirmation

**When:**
- The user clicks the submit button

**Then:**
- The system successfully adds the user to the user database

# 2
**Given:**
- A valid name, password, password confirmation
- A username that already exists in the user database

**When:**
- The user clicks the submit button

**Then:**
- An error message displays notifying the user that the username is taken / already exists

# 3
**Given:**
- A valid name, username, and password
- Password confirmation that does not match the password

**When:**
- The user types in the incorrect password confirmation

**Then:**
- Something turns red / shows an error message that notifies the user that the passwords do not match
